FROM python:3.13.3
WORKDIR /front
COPY requirements.front.txt .
RUN python -m pip install --upgrade pip
RUN python -m pip install --no-cache-dir -r requirements.front.txt
COPY . .
ENV Mydev=QA
EXPOSE 2002
CMD [ "python","-m","streamlit","run","./front.py","--server.address","0.0.0.0","--server.port","2002" ]