FROM python:3.13.3
WORKDIR /app 
COPY requirements.v1.txt /app
RUN python -m pip install --upgrade pip 
RUN python -m pip install --no-cache-dir -r requirements.v1.txt
COPY . .
EXPOSE 101
ENV Myvalue=QA
CMD ["python","-m","streamlit","run","./v1.py","--server.address","0.0.0.0","--server.port","101"] 