FROM python:3.13.3
WORKDIR /App
COPY requirements.back.txt ./
RUN python -m pip install --upgrade pip && \
    python -m pip install --no-cache-dir requirements.back.txt
COPY . .
EXPOSE 1002
ENV Mydev=DEV1
CMD [ "python",'-m','uvicorn','backauth.py:application','--host','0.0.0.0','--port','1002','--workers','4' ]