FROM python:3.13.3
WORKDIR /app 
COPY requirements.txt /app
RUN python -m pip install --upgrade pip 
RUN python -m pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 100
ENV Myvalue=QA
CMD ["python","-m","streamlit","run","./main.py","--server.address","0.0.0.0","--server.port","100"] 
